config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  #root 'tweets#index'
  root to: "static_pages#index"

  scope :api do
    get 'tweets/index', to: 'tweets#index'
    get 'tweets/download', to: 'tweets#download.csv'
    get 'tweets/search', to: 'tweets#search'
    #get 'users/search', to: 'users#search'
    #get 'users/download', to: 'users#download.csv'
    #get 'users/:id', to: 'users#show', as: 'users'
  end

  scope :auth do
    get 'is_signed_in', to: 'auth#is_signed_in?'
  end
  
  get "*path" => "static_pages#index"
end

app/models/tweet.rb
class Tweet < ApplicationRecord

end

app/controllers/tweets_controller.rb
require 'csv'

class TweetsController < ApplicationController
  before_action :get_client
  def get_client

    $client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["TWITTER_CONSUMER_KEY"]
      config.consumer_secret     = ENV["TWITTER_CONSUMER_SECRET"]
      config.access_token        = ENV["TWITTER_OAUTH_TOKEN"]
      config.access_token_secret = ENV["TWITTER_OAUTH_TOKEN_SECRET"]
    end
  end

  def index
    username = 'adamwgoh'
    option = {:count => 3, :include_rts => true}
    @tweets = $client.search("airasia", result_type:'recent').take(3).collect()
    
  end

  def download
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"tweets-list\""
        headers['Content-Type'] ||= Mime::CSV
      end
    end
  end

  def trending
    @trends = $client.trends()
  end

end

#  # GET /tweets
#  # GET /tweets.json
#  def index
#    @tweets = Tweet.all
#  end
#
#  # GET /tweets/1
#  # GET /tweets/1.json
#  def show
#  end
#
#  # GET /tweets/new
#  def new
#    @tweet = Tweet.new
#  end
#
#  # GET /tweets/1/edit
#  def edit
#  end
#
#  # POST /tweets
#  # POST /tweets.json
#  def create
#    @tweet = Tweet.new(tweet_params)
#
#    respond_to do |format|
#      if @tweet.save
#        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
#        format.json { render :show, status: :created, location: @tweet }
#      else
#        format.html { render :new }
#        format.json { render json: @tweet.errors, status: :unprocessable_entity }
#      end
#    end
#  end
#
#  # PATCH/PUT /tweets/1
#  # PATCH/PUT /tweets/1.json
#  def update
#    respond_to do |format|
#      if @tweet.update(tweet_params)
#        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
#        format.json { render :show, status: :ok, location: @tweet }
#      else
#        format.html { render :edit }
#        format.json { render json: @tweet.errors, status: :unprocessable_entity }
#      end
#    end
#  end
#
#  # DELETE /tweets/1
#  # DELETE /tweets/1.json
#  def destroy
#    @tweet.destroy
#    respond_to do |format|
#      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
#      format.json { head :no_content }
#    end
#  end
#
#  private
#    # Use callbacks to share common setup or constraints between actions.
#    def set_tweet
#      @tweet = Tweet.find(params[:id])
#    end
#
#    # Never trust parameters from the scary internet, only allow the white list through.
#    def tweet_params
#      params.require(:tweet).permit(:username, :content)
#    end
#end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/download.csv.erb
<%= keyword = params[:search] %>
<%= @tweets = $client.search(keyword, result_type:'recent').take(200).collect() %>
<%= headers = ['Id', 'Username', 'Created_at','Time Zone','verified', 'Content'] %>
<%= CSV.generate_line headers %>
<%= @tweets.each do |t| %>
<%= CSV.generate_line([t.id, t.user['name'], t.created_at, t.time_zone,t.verified, t.text]).html_safe -%>
<% end -%>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<!-- 
<script>
  ReactJS.render(
  React.createElement(AlertApp),
    document.getElementById('Haha')
  );
</script>
--!>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
    </tr>

    <tr>
      <th>Username</th>
      <th>Created At</th>
      <th>Content</th>
      <th colspan="4"></th>
    </tr>
    <tr>
        <%= form_tag(tweets_search_path, :method => "get", id: "search-form" ) do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search tweets" %>
        <%= submit_tag "Search" %>
        <% end %>
    </tr>
    <tr>
        <%= form_tag(users_search_path, :method => "get", id: "search-user-form" ) do %>
        <%= text_field_tag :search, params[:keyword], placeholder: "Search User" %>
        <%= submit_tag "Search" %>
        <% end %>
    </tr>

  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.user.screen_name %></td>
        <td><%= tweet.created_at  %></td>
        <td><%= tweet.text %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <%= button_to 'Download as CSV', tweets_download_path(format: :csv),  method: :get, params: {search: params[:search]}%>
    </tr>

    <tr>
      <th>Username</th>
      <th>Created At</th>
      <th>Content</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% keyword = params[:search] %>
    <% @tweets = $client.search(keyword, result_type:'recent').take(50).collect() %>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.user.screen_name %></td>
        <td><%= tweet.created_at  %></td>
        <td><%= tweet.text %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tweets/show.csv.erb
<%= headers = ['Username', 'Created_at', 'Content'] =%>
<%= CSV.generate_line headers %>
<%= @tweets.each do |t| -%>
<%= CSV.generate_line([t.username, t.created_at, t.text]) -%>
<% end -%>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @tweet.username %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>