config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  #root 'tweets#index'
  root to: "static_pages#index"

  scope :api do
    get 'tweets/index', to: 'tweets#index'
    get 'tweets/download', to: 'tweets#download.csv'
    get 'tweets/search', to: 'tweets#search'
    #get 'users/search', to: 'users#search'
    #get 'users/download', to: 'users#download.csv'
    #get 'users/:id', to: 'users#show', as: 'users'
  end

  scope :auth do
    get 'is_signed_in', to: 'auth#is_signed_in?'
  end
  
  get "*path" => "static_pages#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:twitter]
	
	def self.find_for_oauth(auth)
	  user = User.where(uid: auth.uid, provider: auth.provier).first
		
		unless user
		  user = User.create(
			  uid:  auth.uid,
				provider: auth.provider,
				email: User.dummy_email(auth),
				password: Devise.friendly_token[0, 20]
			)
		end
		
		user
	end
	
	def self.new_with_session(params, session)
    super.tap do |user|
		  if data = session["devise.twitter_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
				user.email = data["email"] if user.email.blank?
			end
		end
	end

	private

	def self.dummy_email(auth)
	  "#{auth.uid}-#{auth.provider}@example.com"
	end
	
	
	
	
				
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
	 callback_from :twitter
	end

	private 

	def callback_from(provider)
	  provider = provider.to_s

		@user = User.find_for_oauth(request.env['omniauth.auth'])

		if @user.persisted?
			sign_in_and_redirect @user, :event => :authentication
			set_flash_message(:notice, :success, :kind => provider.capitalize) if is_navigational_format?
		else
			session["devise.#{provider}_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
 before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
   def destroy
	   log_out
		 redirect_to root_url
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :get_client
def get_client
  $client = Twitter::REST::Client.new do |config|
    config.consumer_key        = ENV["TWITTER_CONSUMER_KEY"]
    config.consumer_secret     = ENV["TWITTER_CONSUMER_SECRET"]
    config.access_token        = ENV["TWITTER_OAUTH_TOKEN"]
    config.access_token_secret = ENV["TWITTER_OAUTH_TOKEN_SECRET"]
  end
end

def index
  username = 'adamwgoh'
  option = {:count => 3, :include_rts => true}
  @tweets = $client.search("airasia", result_type:'recent').take(3).collect()
end

def search
  username = params[:search]
  @users = $client.user_search(username)
end

def download
  id = params[:users] or params[:id]
  @followers = $client.followers(id.to_i)

  respond_to do |format|
    format.html
    format.csv do
      headers['Content-Disposition'] = "attachment; filename=\"user-list\""
      headers['Content-Type'] ||= Mime::CSV
    end
  end
end

def show
  id = params[:users]
  id ||= params[:id]
  @user = $client.user(id.to_i)
  
  @ids = @followers.ids
  # Check for nof followers if its more than rate limit of 15*5000
  @followers = $client.followers(id.to_i)
  if @user.followers_count > 5000
    # Construct for next cursor
    cursorid = @followers.cursor
    next = $client.user(id.to_id)
  end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/download.csv.erb
<%= @followers = $client.followers(params[:users].to_i) %>
<%= headers = ['Id', 'Username','Description', 'Followers Count', 'Location', 'Is Protected', 'Tweets Posted', 'Most Recent Status', 'Most Recent Status in Reply to', 'Created_at','Time Zone','verified'] %>
<%= CSV.generate_line headers %>
<%= @followers.each do |t| %>
<%= CSV.generate_line([t.id, t.user_name,t.description, t.followers_count, t.friends_count,t.location, t.protected, t.statuses_count, t.status.text, t.status.in_reply_to_screen_name, t.created_at, t.time_zone,t.verified]).html_safe -%>
<% end -%>

app/views/users/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Searched Users</h1>

<table>
  <thead>
    <tr>
      <%= button_to 'Download as CSV', tweets_download_path(format: :csv),  method: :get, params: {search: params[:search]}%>
    </tr>

    <tr>
      <th>Followers</th>
      <th>Following</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% keyword = params[:username] %>
    <% @tweets = $client.search(keyword, result_type:'recent').take(50).collect() %>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.user.screen_name %></td>
        <td><%= tweet.created_at  %></td>
        <td><%= tweet.text %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.screen_name%></h1>
<h1><img src=<%= @user.profile_image_uri.to_s %> /></h1>
<h2>
      <%= button_to 'Download as CSV', users_download_path(format: :csv),  method: :get, params: {users: params[:id]}%>
</h2>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Followed</th>
      <th> Followers</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @user.screen_name %></td>
        <td><%= @user.followers_count %></td>
        <%= @followers.each do |follower| %>
          <tr>
            <td><%= follower.screen_name %></td>
            <td><%= follower.status.text %></td>
          </tr>
        <% end %>
      </tr>
  </tbody>
</table>

app/views/users/user.html.erb
<p id="notice"><%= notice %></p>

<h1>User</h1>
<h1><img src=<%= user.profile_image_uri.to_s %> /></h1>

<table>
  <thead>
    <tr>
      <%= button_to 'Download as CSV', tweets_download_path(format: :csv),  method: :get, params: {search: params[:search]}%>
    </tr>
    <tr>
      <th>User</th>
      <th>Description</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.screen_name, user_path(user.id)%></td>
        <td><%= user.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>